# This is a test for a simple bug easily missable bug.
# The vm keeps track of how many calls it is currently in. This is to prevent
# infinitely recursing calls.
# Foreign calls forget to adjust for a function return dropping it, allowing
# the depth to go into negatives.

define my_apply(input: list[integer]) : list[integer]
{
    input.apply{|i| i}
    return input
}

my_apply(my_apply([1, 2, 3]))
